services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gomj
      POSTGRES_PASSWORD: gomj
      POSTGRES_DB: gomj_wiki
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
